name: Simple workf

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Runs a script
        run: |
          echo "Hello From {{ github.repository.actor}}" 